In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
a = np.array([1,2,3])
type(a), a.shape, a,

(numpy.ndarray, (3,), array([1, 2, 3]))

In [5]:
b = np.array([[1,2,3],[4,5,6]])
b.shape

(2, 3)

In [6]:
a = np.zeros((2,3))
b = np.ones((3,4))
c = np.full((2,3), 7)
a, b, c

(array([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]), array([[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]), array([[7, 7, 7],
        [7, 7, 7]]))

In [9]:
d = a[:,:]
d

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [10]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)
x * y

array([[  5.,  12.],
       [ 21.,  32.]])

In [11]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.dot(x, y)

32

In [14]:
x = np.array([[1,2], [3,4]])
x.T

array([[1, 3],
       [2, 4]])

In [16]:
v = np.array([1,2,3])
w = np.array([4,5])

np.reshape(v, (3, 1)) * w

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])